name: Build and deploy a basic demo node.js Azure function app
on:
  workflow_dispatch:
  push:
    branches:
    - main
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node 12.x Environment
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd .
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: bjdnodejs
        package: '.'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}